name: klusta2
dependencies:
  - python=3.5
  - pip=9.0.1
  - numpy=1.14.2
  - scipy=1.0.0
  - h5py=2.8.0
  - six=1.11.0
  - cython=0.27.3
  - pip:
    - klustakwik2
    - tqdm
    - click
    - colorednoise
